name: pep8-format

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[lint]

      - name: Run format check
        run: ./scripts/format-check.sh

      - name: Run tests
        run: python -m unittest discover
